sudo: required
dist: trusty
language: python
python:
  - 2.7
virtualenv:
  system_site_package: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - python setup.py install

script:
  - python setup.py test

matrix:
  fast_finish: true
